name: Security-js
on: ['push']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Installing dependencies ...
      id: install
      run: npm install
    - name : Checking js security vulnerabilities ...
      id: audit
      run: npm run audit
    - name: Launching js audit fixer ...
      id: fix
      run: echo ${{ steps.audit.outputs.status }}
