name: Security-js
on: ['push']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Installing dependencies ...
      id: install
      run: npm install
    - name : Checking js security vulnerabilities ...
      id: audit
      run: npm audit --json >> test.json
#    - name: Launching js audit fixer ...
#      id: fix
#      run: npm audit fix --force
#      if: failure()
    - name: Processing audit result ...
      id: processing
      run: node ./script.js
      if: failure()
    - name: Remove audit result ..
      id: clean
      run: rm test.json
